-- App switcher: focus app → cycle windows → wrap to first on last window
local function appCycle(bundleID)
  local app = hs.application.find(bundleID)

  if not app then
    hs.application.launchOrFocusByBundleID(bundleID)
    return
  end

  local wins = {}
  for _, w in ipairs(app:allWindows()) do
    if w:isStandard() and not w:isMinimized() then
      table.insert(wins, w)
    end
  end

  if #wins == 0 then
    hs.application.launchOrFocusByBundleID(bundleID)
    return
  end

  if hs.application.frontmostApplication():bundleID() ~= bundleID then
    wins[1]:focus()
    return
  end

  local focused = app:focusedWindow() or hs.window.focusedWindow()
  local curIdx = nil
  if focused then
    for i, w in ipairs(wins) do
      if w:id() == focused:id() then
        curIdx = i
        break
      end
    end
  end

  local nextIdx = ((curIdx or 0) % #wins) + 1
  wins[nextIdx]:focus()
end

hs.hotkey.bind({"option"}, "c", function()
  appCycle("com.google.Chrome")
end)

hs.hotkey.bind({"option"}, "x", function()
  appCycle("net.kovidgoyal.kitty")
end)

-- ── sioyek: monitor-aware window layout ──────────────────────────────────────
-- Sioyek reads prefs_user.config once at startup and has no conditional logic,
-- so we regenerate the live config from the dotfiles "base" config based on which
-- monitors are connected, then launch/focus. No externals -> base config verbatim
-- (the laptop layout). External monitor(s) present -> main window fills the
-- leftmost external, the 2nd (helper) window fills the rightmost external.
local sioyekBundle = "info.sioyek.sioyek"
local sioyekBase   = "/Users/induja/projects/mac_dotfiles/mac/sioyek/prefs_user.config"
local sioyekLive   = os.getenv("HOME") .. "/Library/Application Support/sioyek/prefs_user.config"

-- Window-geometry directives we override when external monitors are present.
local sioyekWindowKeys = {
  main_window_size = true, main_window_move = true,
  helper_window_size = true, helper_window_move = true,
  single_main_window_size = true, single_main_window_move = true,
}

local function readFile(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local c = f:read("*a")
  f:close()
  return c
end

local function writeSioyekLive(contents)
  -- The live config starts life as the dotfiles symlink; remove it before the
  -- first write so we create a real file instead of clobbering the tracked base.
  if hs.fs.symlinkAttributes(sioyekLive) then os.remove(sioyekLive) end
  local f = io.open(sioyekLive, "w")
  if not f then
    hs.alert.show("sioyek: cannot write live config")
    return
  end
  f:write(contents)
  f:close()
end

local function regenSioyekPrefs()
  local base = readFile(sioyekBase)
  if not base then
    hs.alert.show("sioyek: base config not found")
    return
  end

  -- Anything that isn't the built-in panel counts as an external monitor.
  local externals = {}
  for _, s in ipairs(hs.screen.allScreens()) do
    if not s:name():match("Built%-in") then table.insert(externals, s) end
  end

  if #externals == 0 then
    writeSioyekLive(base) -- laptop only: keep the base config exactly as-is
    return
  end

  table.sort(externals, function(a, b) return a:frame().x < b:frame().x end)
  local mainScreen   = externals[1]                 -- leftmost external
  local helperScreen = externals[#externals]        -- rightmost external
  if #externals == 1 then helperScreen = hs.screen.primaryScreen() end -- fall back to built-in

  local m, h = mainScreen:frame(), helperScreen:frame() -- frame() excludes menu bar
  local fmt = function(x) return math.floor(x + 0.5) end

  -- Strip the base file's window-geometry lines; we set our own below.
  local kept = {}
  for line in (base .. "\n"):gmatch("([^\n]*)\n") do
    local key = line:match("^%s*([%w_]+)")
    if not (key and sioyekWindowKeys[key]) then table.insert(kept, line) end
  end

  local block =
    "\n\n# --- generated by Hammerspoon (Option+P): external-monitor layout ---\n"
    .. string.format("# main -> left external (%s); 2nd window -> right external (%s)\n",
                     mainScreen:name(), helperScreen:name())
    .. string.format("main_window_size %d %d\nmain_window_move %d %d\n",
                     fmt(m.w), fmt(m.h), fmt(m.x), fmt(m.y))
    .. string.format("helper_window_size %d %d\nhelper_window_move %d %d\n",
                     fmt(h.w), fmt(h.h), fmt(h.x), fmt(h.y))
    .. string.format("single_main_window_size %d %d\nsingle_main_window_move %d %d\n",
                     fmt(m.w), fmt(m.h), fmt(m.x), fmt(m.y))

  writeSioyekLive((table.concat(kept, "\n"):gsub("%s+$", "")) .. block)
end

hs.hotkey.bind({"option"}, "p", function()
  regenSioyekPrefs()
  appCycle(sioyekBundle)
end)
